#!/bin/sh
# start with:  wget -qO - https://raw.githubusercontent.com/MachoDrone/instcrap/main/instcrap | sudo bash



clear
echo .
lsb_release -a
echo .
echo Should be Ubuntu 22.04 or higher
echo .
sleep 5
sudo apt update -y

sudo apt install apt-transport-https ca-certificates curl software-properties-common -y

sudo rm /usr/share/keyrings/docker-archive-keyring.gpg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update -y

apt-cache policy docker-ce

sudo apt install docker-ce -y

sudo systemctl status docker > statusdocker.tmp
cat statusdocker.tmp
rm statusdocker.tmp


# ****verify $SUDO_USER function************
sudo usermod -aG docker $USER


# ******** work in script?? *********
#sudo su - $USER

# ******************************************

groups

sudo usermod -aG docker $USER
# ****************************************** END OF $SUDO_USER??

docker
docker info
docker images


sudo lshw -c display
sudo lshw -c video
sudo ubuntu-drivers devices
sudo ubuntu-drivers autoinstall
# sudo apt install nvidia-driver-version-number

# Run this shutdown reboot and continue at the next comment
MARKER_FILE="/tmp/reboot_marker"
PROFILE_FILE="$HOME/.profile"
PROFILE_BACKUP="$HOME/.profile.bak"

if [ ! -f "$MARKER_FILE" ]; then
    echo "hello world"

    # Create the marker file to indicate the script has run up to the reboot
    touch "$MARKER_FILE"

    # Backup the current .profile
    cp "$PROFILE_FILE" "$PROFILE_BACKUP"

    # Add command to .profile to continue the script after reboot
    echo "/path/to/your/script.sh" >> "$PROFILE_FILE"

echo -------------------------------
echo rebooting system in 10 seconds
echo -------------------------------
sleep 10

    # Reboot the system
    sudo shutdown -r now

