#!/bin/sh
# start with:  wget -qO - https://raw.githubusercontent.com/MachoDrone/nosnodeinstaller/main/nosnodeinstaller1 | sudo bash


clear
echo .
lsb_release -a
echo .
echo Please observe if you are using Ubuntu 22.04 or higher
echo .
sleep 1
sudo apt update -y

sudo apt install apt-transport-https ca-certificates curl software-properties-common -y

sudo rm /usr/share/keyrings/docker-archive-keyring.gpg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update -y

apt-cache policy docker-ce

sudo apt install docker-ce -y

sudo systemctl status docker > statusdocker.tmp
cat statusdocker.tmp
rm statusdocker.tmp


# ****verify $SUDO_USER function************
sudo usermod -aG docker $USER

echo wget https://raw.githubusercontent.com/MachoDrone/nosnodeinstaller/main/nosnodeinstaller2 > c.sh
chmod +x c.sh

echo TO CONTINUE THE INSTALLATION TYPE: ./c.sh
# ******** work in script?? *********
su - $USER
# su - $USER (this works fine)
# vs sudo su - $USER (doesn't work right? "input divice is not a tty")
# ******************************************
