#!/bin/sh
# start with:  wget -qO - https://raw.githubusercontent.com/MachoDrone/nosnodeinstaller/main/nosnodeinstaller1 | sudo bash


clear
echo .
lsb_release -a
echo .
echo Please ovserve if you are using Ubuntu 22.04 or higher
echo .
sleep 1
sudo apt update -y

sudo apt install apt-transport-https ca-certificates curl software-properties-common -y

sudo rm /usr/share/keyrings/docker-archive-keyring.gpg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-cache policy docker-ce

sudo apt install docker-ce -y

sudo systemctl status docker > statusdocker.tmp
cat statusdocker.tmp
rm statusdocker.tmp


# ****verify $SUDO_USER function************
sudo usermod -aG docker $USER


# ******** work in script?? *********
sudo su - $USER

# ******************************************

groups

sudo usermod -aG docker $USER
# ****************************************** END OF $SUDO_USER??

#docker
#docker info
#docker images

sudo apt install lshw -y
sudo lshw -c display
#sudo lshw -c video
sudo ubuntu-drivers devices
sudo ubuntu-drivers autoinstall
# sudo apt install nvidia-driver-version-number

# Run this shutdown reboot and continue at the next comment
# echo -------------------------------
# echo rebooting system in 10 seconds
# echo -------------------------------
# sleep 10
    # Reboot the system
#    sudo shutdown -r now
# echo THIS IS WHERE IT REBOOTS
