#!/bin/sh

#run with:  wget -qO - https://raw.githubusercontent.com/MachoDrone/instcrap/main/nosnodeinstaller2 | sudo bash

# Continue the script here after reboot

sudo lshw -c display
prime-select query
# sudo prime-select intel
sudo prime-select nvidia


sudo rm /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list \
  && \
    sudo apt-get update

sudo apt-get install -y nvidia-container-toolkit

sudo nvidia-ctk runtime configure --runtime=docker

sudo systemctl restart docker

echo SCRIPT COMPLETE
echo END OF SCRIPT
bash <(wget -qO- https://nosana.io/register.sh)
